export const freqConst = [
  { name: "a", frequency: 0 },
  { name: "b", frequency: 0 },
  { name: "c", frequency: 0 },
  { name: "d", frequency: 0 },
  { name: "e", frequency: 0 },
  { name: "f", frequency: 0 },
  { name: "g", frequency: 0 },
  { name: "h", frequency: 0 },
  { name: "i", frequency: 0 },
  { name: "j", frequency: 0 },
  { name: "k", frequency: 0 },
  { name: "l", frequency: 0 },
  { name: "m", frequency: 0 },
  { name: "n", frequency: 0 },
  { name: "o", frequency: 0 },
  { name: "p", frequency: 0 },
  { name: "q", frequency: 0 },
  { name: "r", frequency: 0 },
  { name: "s", frequency: 0 },
  { name: "t", frequency: 0 },
  { name: "u", frequency: 0 },
  { name: "v", frequency: 0 },
  { name: "w", frequency: 0 },
  { name: "x", frequency: 0 },
  { name: "y", frequency: 0 },
  { name: "z", frequency: 0 },
];
